# Generated by Django 4.0.6 on 2022-07-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='memo',
        ),
        migrations.AlterField(
            model_name='blog',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
