# Generated by Django 4.0.6 on 2022-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_genre_alter_blog_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='genre',
            field=models.CharField(blank=True, choices=[('Indie', 'Indie'), ('Rock', 'Rock'), ('K-pop', 'K-pop'), ('Pop', 'Pop'), ('Else', 'Else')], max_length=10, null=True),
        ),
    ]
